# Generated by Django 2.2.3 on 2019-07-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190715_0719'),
        ('users', '0005_auto_20190715_0627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
