# Generated by Django 2.2.3 on 2019-07-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190722_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followee',
        ),
        migrations.AddField(
            model_name='follower',
            name='followee_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follower',
            name='followee_name',
            field=models.CharField(default='okoko', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
