# Generated by Django 2.2.3 on 2019-07-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190722_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followee',
            new_name='followee_user',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='follower_user',
        ),
    ]
