# Generated by Django 2.2.3 on 2019-07-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190722_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='followee_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='users.User'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.User'),
        ),
    ]
