# Generated by Django 2.2.3 on 2019-07-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190715_1211'),
        ('authentication', '0008_auto_20190715_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Use',
        ),
    ]
