# Generated by Django 2.2.3 on 2019-07-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190715_1211'),
        ('authentication', '0009_auto_20190715_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Use',
            new_name='User',
        ),
    ]
