# Generated by Django 2.2.3 on 2019-07-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190715_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='name',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower_id',
            field=models.IntegerField(default=0),
        ),
    ]
