# Generated by Django 2.2.3 on 2019-07-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20190716_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower_id',
            new_name='followee_id',
        ),
    ]
