# Generated by Django 2.2.3 on 2019-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190716_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='follower',
        ),
        migrations.AddField(
            model_name='follower',
            name='followee_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
